spring:
  application:
    name: my-spring-boot-app
  datasource:
    # 使用OpenTelemetry instrumented driver
    driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
    url: otel:mysql://localhost:3306/mydb
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# OpenTelemetry配置
opentelemetry:
  enabled: true
  service:
    name: ${spring.application.name}
    version: 1.0.0

  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      headers: ${OTEL_EXPORTER_OTLP_HEADERS:}

  # 自定义过滤配置
  filter:
    exclude-urls:
      - "/actuator/health/**"
      - "/actuator/metrics/**"
      - "/actuator/prometheus/**"
      - "/actuator/info/**"
      - "/favicon.ico"
    exclude-operations:
      - "PING"
      - "SELECT 1"
      - "SELECT @@session.tx_read_only"
    exclude-span-names:
      - "jedis.ping"
      - "lettuce.ping"
      - "actuator.health"
      - "connection.ping"

  # HTTP客户端追踪配置
  http-client:
    capture-request-headers:
      - "Authorization"
      - "Content-Type"
      - "Accept"
      - "User-Agent"
    capture-response-headers:
      - "Content-Type"
      - "Content-Length"
      - "Cache-Control"
    capture-request-body: false  # 生产环境建议关闭
    capture-response-body: false # 生产环境建议关闭
    max-body-size: 1024         # 最大记录的body大小(字节)

# RQueue配置
rqueue:
  redis:
    enabled: true
  web:
    enable: true
  metrics:
    count:
      execution: true
      failure: true
    tags:
      - queue
      - status

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

# 日志配置
logging:
  level:
    io.opentelemetry: INFO
    com.github.sonus21.rqueue: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
